server:
  port: 8080

spring:
  application:
    name: ship-service
    version: 1.0.0-SNAPSHOT
    description: Ship service provides the facility to add, update, remove and view the ship details on request
  jpa:
    showSql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/ship-db
    username: sa
    password:
    driverClassName: org.h2.Driver


jwt:
  secret: admin

info:
  appName: ${spring.application.name}
  descripton: ${spring.application.description}
  version: ${spring.application.version}
